name: Build iOS & WatchApp IPA

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build Project for iOS & watchOS
        run: |
          xcodebuild -scheme StrasbourgMap \
                     -sdk iphoneos \
                     -configuration Release \
                     -derivedDataPath build \
                     build